config/routes.rb
# Rails.application.routes.draw do
#   root to: 'users#index'
#   devise_for :users

#   get '/users/', to: 'users#index'
#   get '/users/:id/', to: 'users#show'

#   get '/posts/new', to: 'posts#new'
#   get '/users/:id/posts/', to: 'posts#index'
#   get '/users/:id/posts/:id/', to: 'posts#show'

#   post '/posts', to: 'posts#create'
#   post '/users/:user_id/posts/:id/comments', to: 'comments#create'
#   post '/users/:user_id/posts/:id/likes', to: 'likes#create'
# end

Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'users#index'
  get '/users/', to: 'users#index'
  get '/users/:id/', to: 'users#show'

  get '/posts/new', to: 'posts#new'
  get '/users/:user_id/posts/', to: 'posts#index'
  get '/users/:user_id/posts/:id/', to: 'posts#show'

  post '/posts', to: 'posts#create'
  post '/users/:user_id/posts/:id/comments', to: 'comments#create'
  post '/users/:user_id/posts/:id/likes', to: 'likes#create'
  delete '/users/:user_id/posts/:id', to: 'posts#destroy'
  delete '/users/:user_id/posts/:post_id/comments/:id', to: 'comments#destroy'

  namespace :api, defaults: { format: :json } do
    resources :users, only: %i[index show] do
      resources :posts, only: %i[index show] do
        resources :comments, only: %i[index create]
      end
    end
  end
end

app/views/shared/_comment.html.erb
<h1 class="form-header form-header-comment-new"> Create new comment </h1>

<%= form_with url: comment_create_path, model: Comment do |form| %>
  <%= form.hidden_field :post_id, value: @post.id %>
  <div class="form-wrapper">

    <div class="fields-wrapper">
      <%= form.label :text%>
      <%= form.text_area :text%>
  </div>

  <%= form.submit 'Comment now', :class=>"btn btn-comment" %>

  </div>
<% end %>

app/views/shared/_like.html.erb
<%= form_with url: like_create_path, model: Like do |form| %>
  <%= form.hidden_field :post_id, value: @post.id %>
  <div>
    <%= form.submit "Like", :class=>"btn btn-like" %>
  </div>
<% end %>

app/views/shared/_post.html.erb
<h1 class="form-header form-header-post-new"> Create new post </h1>

<%= form_with model: @post, class:"form-rails ", local: true do |form|%>
  <div class="form-wrapper">
    <div class="fields-wrapper">
      <%= form.label :title%>
      <%= form.text_field :title%>
    </div>

    <div class="fields-wrapper">
      <%= form.label :text%>
      <%= form.text_area :text%>
  </div>

  <%= form.submit 'Post now', :class=>"btn btn-submit" %>

  </div>
<% end %>